import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {DarkModeProvider} from "@/components/providers/DarkModeProvider";
import Header from "@/components/ui/header";
import {Aside} from "@/components/ui/aside";
import Theme from "@/components/ui/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="min-h-full flex flex-col text-zinc-800/75 dark:text-white">
        <DarkModeProvider>
            <div className="min-h-full flex flex-col items-center bg-zinc-100 font-sans dark:bg-zinc-900">
                <Header/>
                <main className="flex flex-1 w-screen h-full items-center justify-center">
                    <Aside/>
                    <section className="min-h-screen w-full max-w-4xl flex-col items-center justify-between py-32 px-16 sm:items-start">
                        <div className="w-full flex items-center justify-center ">
                            {children}
                        </div>
                    </section>
                    <Theme/>
                </main>
            </div>
        </DarkModeProvider>
        </body>
        </html>
    );
}
